### ISSUE TITLE
Location of Terrain .htre files

### ISSUE THREAD

**Issue by DanTsukasa** [youarebritish/FoxKit#20]
Are the .htre files within a container, I've extracted everything and haven't come across one at all.

My guess was that they might be in the ptex files, however all tools convert those straight to .dds files, so that can't be correct.

Any advice on the locations would be much appreciated.

**Comment by youarebritish** [comment]
They can be tricky to find. You can find one in chunk2\Assets\tpp\pack\environ\stagelow\afgh\small_lod0\162\afgh_slod0_162_162.fpk. There's an fpk like that for each small block, and each one contains a .htre file.

**Comment by DanTsukasa** [comment]
Thankyou. I've been away for a while.

Do you think it'll be possible to have textures auto-assigned at any point ? (even if its just the difuse map).

I love this, its true they're not perfect but they're pretty great honestly, and its interesting to see just how many terrain files were used.

I'd like to ask if, there are any plans to support the map from Ground Zeroes at some point in the future.

**Comment by youarebritish** [comment]
Textures are another issue altogether. Terrain isn't an fmdl like the other models in the game and is textured in a completely different way. There is no diffuse map; it uses a lot of control maps in a complicated setup that I don't fully understand in order to texture it. It's something that we're looking into but there's no timeframe on it yet.

I actually have support for the Ground Zeroes terrain format working in my local branch (Cyprus also uses it), but haven't properly merged it in yet. You can grab that version of the importer here: https://github.com/youarebritish/FoxKit/blob/DataSet/FoxKit/Assets/FoxKit/Modules/Terrain/Importer/TerrainTileImporter.cs but it's not at all tested, so use at your own risk.

**Comment by DanTsukasa** [comment]
Thankyou, looking forward to testing this out.
Do you happen to have a roadmap of the intended/upcoming features at all?

Thanks again!

**Comment by youarebritish** [comment]
At the moment, I'm working on getting DataSet (.fox2) support ready for public use. After that, there's a lot I want to do and I'll look into putting up a roadmap.
